src/components/_account-tab.scss

https://git.pepabo.com/suzuri/suzuri/pull/6825
suzuri/suzuriの二要素認証のプルリクで、
app/assets/stylesheets/lib/nachiguro/components/_account-tab.scss
app/assets/stylesheets/lib/nachiguro/components/_card.scss
app/assets/stylesheets/lib/nachiguro/layout/_settings.scss
のファイルでコンフリクトが起きてて、ここと重複しているスタイルを消す作業をやってて、
app/assets/stylesheets/lib/nachiguro/components/_account-tab.scss
のスタイルをここのnachiguroに追加するの忘れてたので、追記しました！！！！

二要素認証設定画面に使ってたスタイル追加

---

src/components/_expansion-card.scss

I added `pointer-event: none;` to the expansion card arrow.
It makes arrow clickable somehow..

Make expansion card arrow clickable

---

src/utility/_device.scss

Since the order of importing CSS was changed and the device utility style was not applied, I fixed it with `!important`.

Add !important to device utility

---

src/components/_icon-button.scss

This doesn't look cool.
(It only happens on android chrome.)

Remove orange highlight on android chrome

---

src/components/_icon-button.scss
src/components/_selectbox.scss

Some of the components looked different from how it should look, so I fixed them.
Icon button needs to be specified solid property.
|before|after|
|---|---|
|<img width="716" alt="スクリーンショット 2020-06-24 19 13 40" src="https://user-images.githubusercontent.com/21121644/85537803-3f5db980-b64f-11ea-9ba3-2f6f9bda4471.png">|<img width="690" alt="スクリーンショット 2020-06-24 19 16 22" src="https://user-images.githubusercontent.com/21121644/85537787-3c62c900-b64f-11ea-9f53-409ac8efcc7d.png">|
I'm not sure why it didn't affect on production...
In nachiguro, autoprefixer didn't work somehow so I added
|before|after|
|---|---|
|<img width="674" alt="スクリーンショット 2020-06-24 19 19 39" src="https://user-images.githubusercontent.com/21121644/85538284-b430f380-b64f-11ea-8ff5-a9086ea70239.png">|<img width="670" …

Fix nachiguro

---

src/components/_modal.scss

add 'ncgr-modal--slide-enter-top'.
Using this class, the modal can appear from above.

add_.ncgr-modal--slide-enter-top

---

src/components/_list-view.scss

Fix List View.
- Replaced the margin in `ncgr-list-tile__trailing` from px to rem.
- Set the color of `ncgr-list-tile__primary-title`.
- Because the display will be collapsed if we use the `<a></a>`.
- The top, bottom, left and right padding of the list tiles are switched by the mediaquery.

Fix List View

---

src/components/_container.scss

Rename the container modifier because the current name is redundant.

Rename the container modifier

---

src/foundation/_color.scss
src/utility/_typography.scss

Secondary label color is too light, make it darker.
Since the difference between the Label Color and Secondary Label Color has been reduced, the Label Color has been darkened by one level.

Fix Label Color

---

src/components/_list-view.scss

Fixed a problem with the appearance of the ListTile when a word goes on forever.

Add ListTile to "word-break: break-all;"

---

src/components/_textfield.scss

Align the start position of the Label with the start position of the value.
<table>
<tr>
<th>BEFORE</th>
<th>AFTER</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

Align the start position of the Label with the start position of the value

---

src/components/_list-view.scss

After applying the ListView component in various places, some problems with hovering became apparent, so I will fix it to fit in all places.
<table>
<tr>
<th>BEFORE</th>
<th>AFTER</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
<table>
<tr>
<th>BEFORE</th>
<th>AFTER</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
It has a system-like feel because it is made according to Material Design guidelines. By adding roundness, I want to add a flavor of Nachiguro's ease and kindness.
<table>
<tr>
<th>BEFORE</th>
<th>AFTER</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
In addition, the hover color is not reflected when in dark mode, which is also fixed.

Update List View Component

---

src/components/_textfield.scss

I made a mistake in https://github.com/pepabo/nachiguro/pull/79.
- I forgot to add the "-."
- I didn't account for the border.
<table>
<tr>
<th>BEFORE</th>
<th>AFTER</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

Fix Textfield label margin

---

src/components/_modal.scss

The modal z-index has a much lower ordinal.

The modal z-index has a much lower ordinal

---

src/components/_app-bar.scss
src/components/_semi-modal.scss

- Use the `.ncgr-app-bar` component instead of the `.ncgr-semi-modal__header`.
- Use the `.ncgr-overlay` component instead of the `.ncgr-semi-modal__overlay`.
- Fixed that the contents of the `.ncgr-app-bar` are displayed protruding when there are contents.

Fix Semi Modal

---

src/components/_app-bar.scss

Force GPU acceleration of the App bar.
This will solve the problem of the App bar flickering when using `-fixed` Modifier in iOS Safari.
Ref: 
https://muffinman.io/blog/ios-safari-scroll-position-fixed/

Force app bar gpu acceleration

---

src/components/_table.scss

`white-space: nowrap;` was required.

Fix table scroll

---

src/components/_list-view.scss

Fix probrem that padding of `ncgr-list-view__expansion-body` breaks when Expansion List is closed.

Fix Expansion-List-View

---

src/components/_selectbox.scss

Fix Selectbox label position.
Align to the same location as the textfield.

Fix Selectbox label position

---

src/components/_selectbox.scss

In case we don't use select tag, `cursor: pointer` is needed in `.ncgr-selectbox`.

Add cursor pointer to Select box

---

src/@inhouse/flavor/variables/_color.scss
src/components/_botan.scss

- Favoriteのボタン色を変更します。
- ButtonのOutlinedの見た目をNachiguro独自に調整します。
- Inhouse本体にFlavorで設定できるようにしようかなとも思ったけど他のサービスでの需要がなさそうなので独自カスタムします。

ButtonのOutlinedの見た目をNachiguro独自に調整する

---

src/components/_app-bar.scss

- 現状のSUZURIだとSemi Modalのように複数のapp-barを持つ場合、--activatedで表示するという仕様があるので、一旦`--activated`がついているときのみ表示するようにします。
- Modal系のコンポーネントをInhouseのコンポーネントに置き換えたら削除します。

app-barは--activatedで表示する

---

_adapter.scss
src/_adapter.scss

Provide nachiguro/adapter as a proxy layer of @inhouse/adapter (just re-exporting).
Any user of nachiguro should be Inhouse-agnostic and just `@use 'nachiguro/adapter' as adapter;`

Provide nachiguro/adapter as a proxy layer of @inhouse/adapter

---

src/_nachiguro.scss
src/components/_selectbox.scss
src/components/_text-field.scss
src/components/_textfield.scss
src/components/_tooltip.scss

- ButtonをInhouse由来のものに新しくしたところ、Textfieldと横並びにしたときにサイズが合わなくなってしまったので、TextfieldをInhouseのFlavorを使用して書き直して、あたらしく"Text field"として追加した。
- labelのレイアウトはアクセシビリティの観点から今後Inhouseで変わる可能性があるが、現状SUZURIではこのレイアウト前提でその他のコンポーネントも設計されているので、一旦これでいく。
- SelectboxもTextfieldのスタイルでまかなえるので統合して、以前のものを非推奨にした。

Text field

---

src/components/_text-field.scss

iOS15でSelectやinputのプリミティブな背景色が適用されてしまうので、Textfieldの`._input`に`background-color: transparent;`を明示的に指定します。

Textfieldのinputにbackground-colorを明示的に指定する

---

src/components/_app-bar.scss

App Bar内のBadgeがitem内にとどまるようにします。
Inhouse側の実装がされるまでの暫定処置です。
これをいれないとカートのBadgeがこのように飛んでしまいます。

App Bar内のBadgeがitem内にとどまるようにする

---

src/components/_card.scss

CardのCoverが画像によって境界がわかりづらくなる場合があるので、下にborderを引きます。

CardのCoverが画像によって境界がわかりづらくなる場合があるので、下にborderを引く
