- package-lock.json
- package.json
Automatically run `npm run build` on precommit hook. Not ideal but may help not to forget commit.
> Build automatically

- src/_nachiguro.scss
- src/_sass-helpers.scss
Move `$ncgr-` variables and `ncgr-asset-url` function to new file.
> Helper partial

- src/layout/_product.scss
This adds new classes to product layout. They will be removed from this package but for now required.
> Add classes for choice carousel items

- src/_nachiguro.scss
`_grid.scss` is used often, so I imported it with `nachiguro.scss`.
> Add grid component

- src/_nachiguro.scss
> Add components

- src/components/_selectbox.scss
Modified selectbox icon style.
> Modified selectbox icon style

- src/_nachiguro.scss
> Add checkbox component

- src/components/_checkbox.scss
> Modify checkbox icon style

- src/_nachiguro.scss
> Add modal component

- src/components/_card.scss
- src/layout/_settings.scss
二要素認証の設定画面のスタイルが聞かなくなったので追加します！
> 二要素認証設定画面のスタイル追加

- src/styleguide.scss
Remove nachiguro-full.scss @import.
> Remove nachiguro-full import

- src/_nachiguro.scss
- src/components/_alert.scss
Since I want to import from various files, add Alert component.
> Add alert component

- docs/assets/_footer.html
- docs/assets/_header.html
- docs/assets/style.css
- docs/markdown_renderer.rb
> Add style for Style guide

- src/components/_share-buttons.scss
> Add LINE button style

- src/components/_selectbox.scss
> Add select box border radius

- src/layout/_header.scss
> Add header brand logo style

- src/components/_selectbox.scss
- src/components/_textfield.scss
I made form width/lign-height look nicer
|before mobile|after mobile|
|---|---|
|<img width="364" alt="スクリーンショット 2020-04-30 11 31 09" src="https://user-images.githubusercontent.com/21121644/80666507-624c7100-8ad7-11ea-9310-d0c0e8208a03.png">|<img width="331" alt="スクリーンショット 2020-04-30 16 06 59" src="https://user-images.githubusercontent.com/21121644/80682011-b3bb2700-8afc-11ea-882b-b2b860a9f37e.png">|
|before PC|after PC|
|---|---|
|<img width="508" alt="スクリーンショット 2020-04-30 11 31 27" src="https://user-images.githubusercontent.com/21121644/80666513-65dff800-8ad7-11ea-9c9f-7cead14c693f.png">|<img width="662" alt="スクリーンショット 2020-04-30 16 06 49" src="https://user-images.githubusercontent.com/21121644/80682028-b74eae00-8afc-11ea-9b4a-49591993b859.png">|
|before|after|
|---|---|
|<img …
> Make forms look better

- src/components/_color-selector.scss
I added a border because the color cannot be determined when the palette is white.
> Add border to color-selector

- src/_nachiguro.scss
- src/layout/_footer.scss
> Add footer style

- src/components/_button.scss
- src/foundation/_color.scss
> buttonにncgr-button--apple を追加する

- src/_nachiguro.scss
- src/components/_breadcrumbs.scss
The breadcrumb component is referenced in multiple places so I will add it to Nachiguro.
> Add breadcrumbs component

- src/_nachiguro.scss
- src/components/_user-card.scss
The User card component is referenced in multiple places so I will add it to Nachiguro.
> Add user card

- src/_nachiguro.scss
- src/components/_separator.scss
The Separator component is referenced in multiple places so I will add it to Nachiguro.
> Add separator

- src/_nachiguro.scss
- src/components/_uploader.scss
The Uploader component is referenced in multiple places so I will add it to Nachiguro.
> Add uploader

- src/_nachiguro.scss
- src/components/_choice-card.scss
The Choice card component is referenced in multiple places so I will add it to Nachiguro.
> Add Choice card

- src/_nachiguro.scss
- src/components/_uploader.scss
- src/utility/_is-sr-only.scss
- src/utility/_is-visible.scss
スクリーンリーダー等で読み込ませる要素のためのクラスを追加しました。
> .ncgr-sr-onlyを追加する

- src/components/_selectbox.scss
> Add disabled option style

- src/components/_alert.scss
I updated it to make alert component able to use headings and links.
|before|after1|after2|
|---|---|---|
|<img width="665" alt="スクリーンショット 2020-09-28 19 28 15" src="https://user-images.githubusercontent.com/21121644/94421631-d000e400-01c0-11eb-9b0d-43b1469d3333.png">|<img width="652" alt="スクリーンショット 2020-09-28 19 28 24" src="https://user-images.githubusercontent.com/21121644/94421645-d2fbd480-01c0-11eb-8753-48465bdd9176.png">|<img width="653" alt="スクリーンショット 2020-09-28 19 28 32" src="https://user-images.githubusercontent.com/21121644/94421656-d727f200-01c0-11eb-8ab1-58e7d35a7ba8.png">|
||bold -> normal|more flexible|
> Update alert component

- README.md
- package.json
Add npm run scripts for Styleguide.
It's hard to run it every time, so we run it all together.
> Add npm run scripts for Styleguide

- src/components/_list-view.scss
- src/components/_semi-modal.scss
It repairs `Semi-Modal` components.
> Repair semi modal

- package.json
- src/_nachiguro.scss
- src/components/_container.scss
Add container component for grid.
> Add container

- src/components/_semi-modal.scss
This adds animations to semi-modal.
> Add semi modal animation

- src/components/_semi-modal.scss
> Fix semi-modal

- src/components/_container.scss
- src/components/_grid.scss
Default is mobile size.
Totally completely mobile first.
> Fix default grid gap key

- src/utility/_typography.scss
add utility, `ncgr-typography-label`.
> add typography-label

- src/components/_semi-modal.scss
This fixed an unexpexted fade animation occurred every time the `-active` header, and an animation of box-shadow.
> Fix semi modal animation

- src/components/_container.scss
- src/components/_section.scss
Remove the section inner component as it will be replaced by the container component.
In addition, there was a suggestion that the Large size of the Container might be too small, so we increased the Large size.
> Remove section inner

- docs/assets/_footer.html
- docs/assets/_header.html
- docs/assets/style.css
- docs/markdown_renderer.rb
- src/components/_section.scss
- src/components/_sheet.scss
https://github.com/pepabo/nachiguro/pull/73 change was causing Styleguide to display incorrectly, so it has been fixed.
> Fix styleguide

- src/components/_semi-modal.scss
- src/components/_textfield.scss
Fixed a probrem that `ncgr-textfield__label` hides behind `ncgr-textfield__input` in semi-modal.
> Fix textfield

- src/components/_textfield.scss
Add warning modifier to textfield
> Add warning modifier to textfield

- src/components/_app-bar.scss
Add hover state to floating icon button.
> Add hover state to floating icon button

- docs/assets/_footer.html
- src/components/_app-bar.scss
- src/components/_card.scss
- src/components/_dialog.scss
- src/components/_full-modal.scss
- src/components/_icon-button.scss
- src/components/_product-card.scss
- src/components/_semi-modal.scss
- src/layout/_header.scss
Fix Icon Button.
- Rename Modifier
- Subdivide Modifier
- Replace `.ncgr-app-bar__icon`
> Fix Icon Button

- src/components/_list-view.scss
- Add description of ListView.
- Fix padding of `.ncgr-list-tile__expansion-body`.
> Fix expansion list

- src/_nachiguro.scss
- src/components/_list-view.scss
- src/components/_switch.scss
- src/foundation/_color.scss
Add Switch component.
I will replace the current Switch with this one for the following reasons.
- The current Switch is not very common looking.
- I want to use it in combination with ListView.
> Add Switch component

- src/components/_avatar.scss
> Fix avatar

- src/components/_checkbox.scss
> Fix Checkbox

- src/components/_heading.scss
- Fix heading modifier.
- px to rem
> Fix heading modifier

- src/components/_checkbox.scss
- src/components/_list-view.scss
Fix width of `ncgr-list-tile__leading`.
> Fix ListTile Leading

- src/_nachiguro.scss
- src/components/_tooltip.scss
> Add tooltip

- src/utility/_typography.scss
Add  `ncgr-typography-primary`
> Add ncgr-tyography-primary

- src/components/_semi-modal.scss
Fix open animation of Semi-Modal.
> Fix Semi-Modal animation

- src/components/_product-card.scss
Add height:auto to `.ncgr-product-card__pickup-badge img`
> Add height:auto to `.ncgr-product-card__pickup-badge img`

- src/components/_icon-button.scss
- src/components/_list-view.scss
Fixed a problem when holding ListView an IconButton on a mobile device, behaviors of `:hover` remains.
> Fix hover effect

- src/components/_app-bar.scss
- src/components/_grid.scss
- src/components/_icon-button.scss
- src/components/_list-view.scss
- src/components/_radio.scss
- src/components/_switch.scss
https://sass-lang.com/documentation/breaking-changes/slash-div
> Avoid using slash as a division operator

- src/components/_product-card.scss
Add `ncgr-product-card__user-name` on Product Card component.
> Update Product Card

- src/components/_switch.scss
- src/foundation/_color.scss
> Disabled switch

- src/components/_button.scss
- src/foundation/_color.scss
> Add LINE button

- docs/assets/_header.html
- package.json
- src/@inhouse/flavor/variables/_sizing.scss
- src/components/_container.scss
> Inhouse Container

- package-lock.json
- package.json
Bump inhouse to fix lockfileVersion 2 peerDependecy installation problem.
> bump inhouse to 0.7.2

- src/@inhouse/flavor/_mixins.scss
- src/@inhouse/flavor/variables/_typography.scss
- src/_nachiguro.scss
- src/foundation/_reset.scss
- src/foundation/_typography.scss
> font-familyをInhouse経由で指定する

- package-lock.json
- package.json
- src/@inhouse/flavor/variables/_sizing.scss
- src/components/_checkbox.scss
> Inhouse checkbox

- package-lock.json
- package.json
- src/@inhouse/flavor/variables/_sizing.scss
- src/components/_radio.scss
> Inhouse Radio

- package-lock.json
- package.json
- src/components/_table.scss
> Inhouse table

- package-lock.json
- package.json
- src/@inhouse/flavor/variables/_color.scss
- src/@inhouse/flavor/variables/_sizing.scss
- src/_nachiguro.scss
- src/components/_interactive-table.scss
> Inhouse interactive table

- package-lock.json
- package.json
- src/components/_list.scss
> Inhouse list

- package-lock.json
- package.json
- src/components/_avatar.scss
> Inhouse avatar

- src/_nachiguro.scss
- src/components/_icon.scss
> Add Inhouse icon

- package-lock.json
- package.json
> Update Inhouse Components

- package-lock.json
- package.json
- src/@inhouse/flavor/variables/_color.scss
- src/@inhouse/flavor/variables/_elevation.scss
Update inhouse components v0.16.0
> Update inhouse components v0.16.0

- docs/assets/_footer.html
- package-lock.json
- package.json
- src/@inhouse/flavor/variables/_color.scss
- src/_nachiguro.scss
- src/components/_alert.scss
- src/components/_checkbox.scss
- src/components/_full-modal.scss
- src/components/_interactive-list.scss
- src/components/_radio.scss
- src/components/_semi-modal.scss
> Inhouse interactive list

- package-lock.json
- package.json
- src/components/_app-bar.scss
> Inhouse app bar

- docs/assets/_footer.html
- package-lock.json
- package.json
- src/components/_app-bar.scss
- src/components/_dialog.scss
- src/components/_full-modal.scss
- src/components/_semi-modal.scss
- Inhouseのバージョンをv0.20.1にアップグレードしました。
- Inhouse側でApp Barの変更があったので、仕様に合わせてマークアップを修正しました。
- 抜け漏れていたスタイルガイドの修正も行いました。
> App Barのマークアップを修正

- package-lock.json
- package.json
Update Inhouse Components v0.25.1
> Update Inhouse Components v0.25.1

- src/components/_avatar.scss
> Add Skeleton Avatar

- src/components/_botan.scss
> Add Skeleton Button

- src/components/_checkbox.scss
> Skeleton Checkbox

- src/components/_radio.scss
> Skeketon Radio

- src/components/_interactive-list.scss
> Skeleton Interactive List

- src/components/_interactive-table.scss
> Skeleton Interactive Table

- package-lock.json
- package.json
Inhouse Components Web v0.26.0
> Inhouse Components Web v0.26.0

- package.json
- src/components/_heading.scss
> Fix Heading

- src/components/_text-field.scss
https://github.com/pepabo/nachiguro/pull/173 でModifierを分離できてなかったので、Modifierも分離します。
> Fix text field

- src/components/_text-field.scss
text-fieldのinputのwebkit-appearanceが消せてなかったので修正しました
> text-fieldのinputのwebkit-appearanceが消せてなかった

- src/components/_text-field.scss
Text fieldにAlign Modifierを追加します。
> Text fieldにAlign Modifierを追加する

- package-lock.json
- package.json
- src/components/_heading.scss
- src/components/_skeleton.scss
- `skeleton-text` mixinの居場所が変わったのに対応した。
> Update inhouse components v0.30.0

- package-lock.json
- package.json
Update Inhouse Components Web v0.31.0
> Update Inhouse Components Web v0.31.0

- package-lock.json
- package.json
Inhouse Components Web v0.32.0
> Inhouse Components Web v0.32.0

- docs/assets/_footer.html
- package-lock.json
- package.json
- src/components/_app-bar.scss
- src/components/_dialog.scss
- src/components/_full-modal.scss
- src/components/_semi-modal.scss
Inhouse components web v0.33.0
> Inhouse components web v0.33.0

- package-lock.json
- package.json
Update Inhouse Components Web v0.34.0
> Update Inhouse Components Web v0.34.0

- package-lock.json
- package.json
- src/_nachiguro.scss
- src/components/_side-navigation.scss
InhouseのSide Navigationコンポーネントを追加します。
> InhouseのSide Navigationコンポーネントを追加

- package-lock.json
- package.json
- src/_nachiguro.scss
- src/components/_bottom-navigation.scss
InhouseのBottom Navigationコンポーネントを追加します。
> InhouseのBottom Navigationコンポーネントを追加

- src/components/_botan.scss
Facebook用のButtonが必要になったので追加します。
> FacebookのButtonを追加する

- package-lock.json
- package.json
Inhouseを最新にします。
色をチェックするhelper関数の仕様が変更されていますが、Nachiguroで対応することはないのでバージョンのアップだけになります。
> Inhouseを最新にする

- docs/assets/_header.html
> fix app-bar in styleguide

- src/components/_full-modal.scss
Fix Full Modal when inactive in Safari.
> Fix Full Modal when inactive in Safari

- src/components/_breadcrumbs.scss
パンくずリストを各ページに設置するため、構造を整える
デザインが破綻していないか
> breadcrumbsを整える

- src/components/_full-modal.scss
> Replace fill-available to stretch
